version: "3"

services:
  app:
    build: ./app
    volumes:
      - ./app/src:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=news
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=vagrant
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
